fix: disable auto-commit by default
kestra-io/plugin-kafka pull request #43
Opened 2023-12-22 13:40 UTC by loicmathieu

Disable kafka-autocommit by default to avoid committing offset if the tas fail.

2023-12-22 13:41 UTC, tchiotludo requested changes

2023-12-22 13:41 UTC, tchiotludo commented on src/main/java/io/kestra/plugin/kafka/AbstractKafkaConnection.java
> +        if (!properties.contains(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG)) {
Must be done only for when using a consumer group

2023-12-22 13:45 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/kafka/AbstractKafkaConnection.java
> +        if (!properties.contains(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG)) {
When no consumer group, this is already the default as there will not be any auto commit (or more precisely, this setting is ignored as the offsets must be handled manually)

2023-12-22 15:57 UTC, tchiotludo commented on src/main/java/io/kestra/plugin/kafka/AbstractKafkaConnection.java
> +        if (!properties.contains(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG)) {
yes I know, but explicit is good and more readable

2023-12-28 10:11 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/kafka/AbstractKafkaConnection.java
> +        if (!properties.contains(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG)) {
@tchiotludo I changed as per your request.

2023-12-28 11:19 UTC, merged